# Generated by Django 3.1 on 2020-08-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200819_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.SmallAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
